package lk.ijse.meatShop.util;
public enum Routes {
    OWNER,LOGIN,ADDEMPLOYEE,UPDATEEMPLOYEE,VIEWEMPLOYEE,ADDITEM,ADDSUPPLIER,FEEDBACK,VIEWSUP,ADDTOSHOWCASE,BUYITEM,PAYMENT,
    CHASHIER,CUSTOMER,ORDERVIEW
}
